#!/bin/bash

export LC_CTYPE=en_US.UTF-8

export PATH="/usr/local/sbin:$PATH"
alias tmux="TERM=xterm-256color tmux"

# let there be color
export CLICOLOR=1

# enable color support of grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias crontab='VIM_CRONTAB=true crontab'
alias updatedb=/usr/libexec/locate.updatedb
alias chmodfolders='find . -type d -exec chmod 755 {} +'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias hg='history | grep'
alias kboff='sudo kextunload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext/'
alias kbon='sudo kextload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext/'
alias pc='pwd | pbcopy'
alias gr='grep --exclude-dir="log" --exclude-dir="tmp" --exclude-dir="./public" -R'
alias ssha="ssh alpha.ymme.info"
alias sshm="ssh mail.ymme.info"

# pretty prompt
[ -r ~/.bash_prompt ] && source ~/.bash_prompt

# vi mode
#set -o vi
#set show-mode-in-prompt On

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

alias mocha="mocha --require mocha-clean"
