recipes:
    mac_os_x:

        ###############################################################################
        # General                                                          #
        ###############################################################################

        - osxdefaults::disable_auto-correct
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete

        - osxdefaults::save_to_disk_not_to_iCloud_by_default
        - osxdefaults::restart_automatically_if_the_computer_freezes
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row

        ###############################################################################
        # Screen                                                                      #
        ###############################################################################

        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop

        ###############################################################################
        # Menu Bar                                                                    #
        ###############################################################################

        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date

        ###############################################################################
        # FINDER                                                                      #
        ###############################################################################

        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_unhide_home
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_set_preferred_view_style
        - osxdefaults::disable_disk_image_verification

        ###############################################################################
        # Dock, Dashboard, and hot corners                                            #
        ###############################################################################

        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock

        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::do_not_show_dashboard_as_a_space

        ###############################################################################
        # Safari & WebKit                                                             #
        ###############################################################################

        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::enable_safari_debug_menu

        ###############################################################################
        # Time Machine                                                                #
        ###############################################################################

        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume

        ###############################################################################
        # Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
        ###############################################################################

        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::tap_to_click
        - osxdefaults::increase_sound_quality_for_bluetooth_headphones
        - osxdefaults::disable_natural_scrolling
